name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "40 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has been no activity on this issue for more than 60 days. If there is no further activity in the next 7 days then it will be closed.'
        stale-pr-message: 'There has been no activity on this pull request for more than 60 days. If there is no further activity in the next 7 days then it will be closed.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
